platform :ios, '8.4'
use_frameworks!

pod 'MJRefresh', '~> 1.4.0'
pod 'AFNetworking', '~> 2.5.1'
pod 'JSONKit', '~> 1.5pre'
pod 'ionicons'
pod 'THCalendarDatePicker', '~> 1.2.0'
pod 'EGOCache', '~> 2.1.3'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'StarWars', '~> 1.0'
pod 'DGElasticPullToRefresh_CanStartLoading'
pod 'SWTableViewCell', '~> 0.3.7'
pod 'Charts', '~> 2.1.6'
pod 'ReactiveCocoa', '~> 4.0.0-RC.1'
